### ISSUE TITLE
Reproduce other KD methods on Res50->MobileNetV2

### ISSUE THREAD

**Issue by NickiJQ** [winycg/HSAKD#11]
I reproduced your method on Res50->MobileNetV2 and got 79.24 top-1 acc, that's awesome. But I reproduce other KD methods SSKD 、CRD... ，I found that my results were nearly to their paper, but were very different from your paper results.(For example, I used SSKD and got acc 72.46, SSKD paper 72.57, your paper 78.21). Could you tell me why? Thanks!

**Comment by winycg** [comment]
Sorry for the late response. My baseline is higher than the SSKD paper, SSKD is  65.79, our result is 73.51. This is because we use a different version of MobileNetV2. Therefore, our distilled result is higher than SSKD.

**Comment by NickiJQ** [comment]
Thanks for your response, for a fair comparison, could you give me the results used general MobileNetV2 by your method, or if I want to get distillation result on general MobileNetV2 by your method, could you give me some advice about parameter setting or just keep as code?

**Comment by winycg** [comment]
You can follow the experimental results with our HSAKD paper. In this paper, we also re-implement MobileNetV2 with SSKD, and achieve 78.21% accuracy.
