### ISSUE TITLE
About the model size

### ISSUE THREAD

**Issue by Nusselder9** [winycg/HSAKD#2]
Hi, thanks for your cool work!

The released resnet18 checkpoint ' resnet18_imagenet_aux_best.pth.tar' has a size of about 452M, which is much larger than the original one (44.7M). What is the difference between them?

Thanks!

**Comment by winycg** [comment]
Thanks for your attention! The original resnet18 checkpoint (44.7M) is downloaded from the official torchvision lib corresponding to the original ResNet-18 architecture. Our released 'resnet18_imagenet_aux_best.pth.tar' contains the weights of our training graph including the original ResNet-18 and its auxiliary branches.
