### ISSUE TITLE
self-supervised lable construction

### ISSUE THREAD

**Issue by wangqiim** [winycg/HSAKD#3]
Thanks for your work. I want to know how to use self-supervised learning in this code. Do you implement self-supervised leanring through following code?
https://github.com/winycg/HSAKD/blob/741a951d5f3f8dda503cbd10d414446434300945/train_teacher_cifar.py#L201
Howerver, I think it is supervised learning label in above code?

**Comment by winycg** [comment]
Thank you for your attention of our work. In fact, the labels are self-supervised (4 rotations) augmented labels over the original supervised labels. Assuming the number of the original supervised labels is N {0,1,...,N-1}, the number of self-supervised augmented labels would become 4*N {(0×4+0,0×4+1,0×4+2,0×4+3), (1×4+0,1×4+1,1×4+2,1×4+3), ..., ((N-1)×4+0,(N-1)×4+1,(N-1)×4+2,(N-1)×4+3)}={0,1,...,4N-1}. The "labels " denotes the self-supervised augmented labels with the label space of 4N. Thanks!

**Comment by wangqiim** [comment]
Make sense. Cool!
