### ISSUE TITLE
The meanings of ss_acc

### ISSUE THREAD

**Issue by MuHeDing** [winycg/HSAKD#4]
I found the ss_acc1 and class_acc1 in your output .I want to ask a question the meanings of ss_acc1 ?

**Comment by winycg** [comment]
Thanks for your attention！ss_acc1 is the Top-1 accuracy over self-supervised augmented distribution with the label space of N*M. 
It means that the model needs to classify both the supervised object category and the self-supervised rotation for a given transformed image.

**Comment by winycg** [comment]
If you have further problems, please feel free to post your questions. Thanks!

**Comment by MuHeDing** [comment]
thanks. I have no problem




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "winycg/HSAKD"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年11月16日(星期二) 下午4:21
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [winycg/HSAKD] The meanings of ss_acc (Issue #4)





 
If you have further problems, please feel free to post your questions. Thanks!
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
