### ISSUE TITLE
the meaning of ss_accuracy、class_accuracy、best_accuracy

### ISSUE THREAD

**Issue by LingFengGold** [winycg/HSAKD#5]
There are 3 values after ss_accuracy, 4 values after class_accuracy, and finally there is a best_accuracy. What are the meanings of these values
<img width="465" alt="Screen Shot 2021-12-05 at 8 54 29 AM" src="https://user-images.githubusercontent.com/85066551/144729230-4f7c0ca5-0757-433f-83a6-1d94a8d7bc04.png">
?

**Comment by winycg** [comment]
Thanks for your attention. We use CIFAR-100 dataset with N=100 supervised classes and 4 rotations as self-supervision augmentation with M=4 self-supervised classes. 
(1) **ss_accuracy** denotes the accuracy over self-supervised augmented distribution with the label space of N*M. 3 values correspond the results of 3 auxiliary classifiers.
(2) **class_accuracy** denotes the original supervised class accuracy with the label space N. 4 values includes the first 3 values of 3 auxiliary classifiers and 1 value of the final classifier. 
(3) In the script of _train_teacher_cifar.py_ , we use **best_accuracy** to represent the best ss_accuracy among 3 values through the overall training process..  In the script of _train_student_cifar.py_ , we use **best_accuracy** to represent the best class_accuracy of the final classifier through the overall training process. The meaning of **best_accuracy** depend on the return value in the final row of  _def test()_ .

**Comment by LingFengGold** [comment]
Thank u !!!
