### ISSUE TITLE
Report the mean result with a standard deviation over 3 times? What do you mean by this? Can you please explain this? 

### ISSUE THREAD

**Issue by Tariq195** [winycg/HSAKD#7]
I have also asked question there on your email, please reply me.

**Comment by winycg** [comment]
We report the mean result on **_the student networks_** with a standard deviation over 3 times. For a teacher network, we only run one time to obtain a pre-trained teacher network.

**Comment by winycg** [comment]
The mean result is the averaged result over several attempts. Your practice is correct.

**Comment by Tariq195** [comment]
Thank you!!!
