### ISSUE TITLE
About training time.

### ISSUE THREAD

**Issue by zorrocai** [winycg/HSAKD#8]
Hi, thanks for your wonderful work.  We wonder about the detailed training GPU device and training time. And we train the model on 6 GeForce 3090 for now, it will take about 2 hours per epoch.

**Comment by winycg** [comment]
Hi, thanks for your attention! I would like to know the detailed experimental dataset and the network pair, or run which py file. Is your experiment conducted on ImageNet?

**Comment by zorrocai** [comment]
Thanks for your reply.  We trained on ImageNet with ResNet34 aux teacher.  The python script that is run is train_teacher_imagenet.py.

**Comment by winycg** [comment]
Hi, the pre-training of ResNet34_aux on ImageNet is indeed time-consuming.  The training time is about ~2.5h/epoch on two Tesla V100 GPUs. We provide the pre-trained checkpoint of ResNet34_aux in the [README.md]. The KD process of ResNet18_aux with the supervision of the pre-trained ResNet34_aux is relatively quick. It consumes ~1.2h/epoch on three RTX 3090 GPUs according to our empirical study.

**Comment by zorrocai** [comment]
Great, we got it. Thanks for your detailed reply :).
