### ISSUE TITLE
the rule of modifying the auxiliary classifiers for a new model

### ISSUE THREAD

**Issue by bendanzzc** [winycg/HSAKD#9]
Hi, Thanks for your work , it is helpfue for me.

I read the auxiliary classifiers code for different model and find there is various between different model. could you tell me the rule for modifying new auxiliary classifiers? Thx a lot

**Comment by winycg** [comment]
Thanks for your attention! The rule is simple. The design of the micro-block is the same as the block in the original network. And the number of stacked blocks is also consistent with the backbone network.
The detailed guideline has shown in the appendix B of our ArXiv paper: [https://arxiv.org/pdf/2107.13715.pdf](url)
If you have any further questions, please feel free to contact me.
